# BridgeRNA gene-property prediction benchmark

## Phase 1: published-benchmark audit

This notebook is deliberately limited to the audit gate. No BridgeRNA inference, model training, or downstream evaluation has been run. The README is the detailed protocol record.

In [1]:
from pathlib import Path
import json
import pandas as pd

root = Path.cwd()
if root.name == 'gene_property_prediction':
    bench = root
else:
    bench = root / 'benchmarks' / 'gene_property_prediction'
audit = pd.read_csv(bench / 'results/audit/published_benchmark_audit.csv')
details = json.loads((bench / 'results/audit/audit_details.json').read_text())
audit

,benchmark,task_type,label_resource,input_resource,reported_metric,exact_labels_obtainable,exact_protocol_status,bridge_overlap
0,BulkFormer gene essentiality,sample-conditioned continuous per-gene depende...,"gene_essentiality_score.pkl (159.1 MB, Zenodo ...","gene_essentiality_expr_data.pkl (166.6 MB, sam...",mean Pearson correlation coefficient (0.186 fo...,True,PARTIAL: exact matrices recovered; preprint sa...,14456/17910 target genes; 14761/18757 input genes
1,Geneformer dosage sensitivity,binary classification of dosage-sensitive vs d...,dosage_sensitivity_TFs.pickle,"10,000 random cells from a 50,000-cell Genecor...",ROC AUC (0.91 in paper),True,"RECOVERED: 5-fold stratified gene CV, shuffled...",245/490 total; 119/122 sensitive; 126/368 inse...
2,GeneCompass dosage sensitivity,"same binary TF dosage-sensitivity task, follow...",No separate labels distributed in current offi...,"10,000 random single-cell transcriptomes",ROC AUC (~0.95 in paper figure/text),True,PARTIAL: paper specifies Geneformer protocol/1...,Same exact Geneformer labels if protocol ident...

In [2]:
labels = pd.read_csv(bench / 'data/processed/geneformer_dosage_sensitivity_labels.csv')
pd.crosstab(labels['published_class'], labels['maps_to_bridgerna'], margins=True)

maps_to_bridgerna       False  True  All
published_class
Dosage-insensitive TFs    242   126  368
Dosage-sensitive TFs        3   119  122
All                       245   245  490

## Gate decision

BulkFormer essentiality is a continuous dependency-score task, not an essential/nonessential classifier. Its exact matrices are available, but key split/readout details remain unresolved. Geneformer labels are exact and recoverable; only 245/490 map to the unchanged BridgeRNA ortholog vocabulary. Context-averaged inference remains deferred until the reference cohort and cost are approved.